#!/bin/sh

ecmd="echo "; i=$(basename $0); if [ -x /etc/custom/custfunc.sh ]; then . /etc/custom/custfunc.sh; ecmd="echm ${i} "; fi
D="`date +%Y%m%d-%H%M`"





#test -f /root/.firstboot.$i && exit 0




INIFILE="/root/wrt.ini"; #if [ -f "$INIFILE" ]; then . "$INIFILE"; else $ecmd "no $INIFILE"; fi
eval $(grep '^OPKGFEEDS_EXTRA_V2RAYA=' $INIFILE | head -n1)


if [ -z "$OPKGFEEDS_EXTRA_V2RAYA" ]; then
	V2RAYA_MSG="${V2RAYA_MSG} [ini-off]"
	#exit 0
elif [ -z "$OPKGFEEDS_EXTRA_V2RAYA" ] && [ "$1" = "force" ]; then
	OPKGFEEDS_EXTRA_V2RAYA="force"
	V2RAYA_MSG="${V2RAYA_MSG} [force]"
fi










if [ "$1" = "disable" ]; then
	

	#sed -i '/v2raya/d' /etc/opkg/customfeeds.conf && $ecmd "disable-feed"
	#rm /etc/opkg/keys/94cc2a834fb0aa03 2>/dev/null && $ecmd "disable-key"

	V2RAYA_MSG= #NEEDED as NO-INI var


	if grep -q 'v2raya' /etc/opkg/customfeeds.conf; then
		sed -i '/v2raya/d' /etc/opkg/customfeeds.conf
		V2RAYA_MSG="${V2RAYA_MSG} [disable-feed]"
	else
		:
	fi


	rm /etc/opkg/keys/94cc2a834fb0aa03 2>/dev/null && V2RAYA_MSG="${V2RAYA_MSG} [disable-key]"


	if [ -z "$V2RAYA_MSG" ]; then
		V2RAYA_MSG="${V2RAYA_MSG} [notenabled]"
	fi



	OPKGFEEDS_EXTRA_V2RAYA=

	#exit 0 #OPKGFEEDS_EXTRA_V2RAYA=

fi
#$ecmd "disable"















###################################################################33
if [ ! -z "$OPKGFEEDS_EXTRA_V2RAYA" ]; then





if grep -q "v2raya" /etc/opkg/customfeeds.conf; then

	#$ecmd "v2raya feed [present]"
	V2RAYA_MSG="${V2RAYA_MSG} [feed-present]"
	#exit 0

else

	V2RAYA_MSG="${V2RAYA_MSG} [feed-add]"
	#$ecmd "v2raya feed [add]"
	echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")" >> "/etc/opkg/customfeeds.conf"
	
	### echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")" | tee -a "/etc/opkg/customfeeds.conf"


fi




if [ ! -f /etc/opkg/keys/94cc2a834fb0aa03 ]; then
	#$ecmd "v2raya key [add]"
	V2RAYA_MSG="${V2RAYA_MSG} [key-add]"

cat << EOF > /etc/opkg/keys/94cc2a834fb0aa03
untrusted comment: Public usign key for v2rayA builds
RWSUzCqDT7CqA+u/9hvcT3Hkw3fUc1dYnpsLmIsayjPmsZM5NjYKYiHW
EOF
chmod +x /etc/opkg/keys/94cc2a834fb0aa03

else
	#$ecmd "v2raya key [present]"
	V2RAYA_MSG="${V2RAYA_MSG} [key-present]"
fi




fi
###################################################################33













$ecmd "$V2RAYA_MSG"



















exit 0

#sed -i '/v2raya/d' /etc/opkg/customfeeds.conf
#rm /etc/opkg/keys/94cc2a834fb0aa03




















echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")" | tee -a "/etc/opkg/customfeeds.conf"


echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")"













exit 0












#wget-ssl https://osdn.net/projects/v2raya/storage/openwrt/v2raya.pub  -O /etc/opkg/keys/94cc2a834fb0aa03

############## Mirror
############## wget-ssl https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/v/v2/v2raya/openwrt/v2raya.pub -O /etc/opkg/keys/94cc2a834fb0aa03





###### Import v2rayA feed

echo "src/gz v2raya https://osdn.net/projects/v2raya/storage/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")" | tee -a "/etc/opkg/customfeeds.conf"

### Mirror
#### echo "src/gz v2raya https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/v/v2/v2raya/openwrt/$(. /etc/openwrt_release && echo "$DISTRIB_ARCH")" | tee -a "/etc/opkg/customfeeds.conf"





### Update feeds
opkg update



####Install v2rayA and its dependencies
opkg install v2raya

# Choose a core you'd like to use, v2ray or Xray
# If you have both installed, the former is preferred by default
opkg install v2ray-core
# opkg install xray-core

# Optional
# opkg install v2fly-geoip v2fly-geosite









### How to use

#Setup v2rayA

# For advanced usage, please see /etc/config/v2raya
uci set v2raya.config.enabled='1'
uci commit v2raya







############3Start v2rayA
/etc/init.d/v2raya start




#################Visit v2rayA webUI and enjoy
http://openwrt.lan:2017




















#sed '/^[A-Z]*$/d' /etc/opkg/customfeeds.conf
#sed -i '/v2raya/d' /etc/opkg/customfeeds.conf



#OPKGFEEDS_EXTRA_V2RAYA=1 ./53-customrepo-v2raya



